// tools/render.mjs
//
// `storyboard.json` -> `storyboard.md`. Čitljiv ljudski prikaz, ništa više (C08).
//
//   node tools/render.mjs episodes/<slug> [--stdout]
//
// Dva pravila koja ovaj alat drže upotrebljivim, oba iz docs/plan/C08-render-i-shotlist.md:
//
//   1. `storyboard.md` se nikad ne piše ni menja ručno — otud DO-NOT-EDIT zaglavlje u prvom redu.
//   2. U `.md` ne ulazi ništa čega nema u `storyboard.json`. Prvi put kad prikaz ponese
//      sopstvenu informaciju, dva prikaza se razilaze i render postaje beskoristan. Zato ovaj
//      alat ne otvara `episode.json` (imena likova, `locked_description`) niti ijedan drugi fajl.
//      Sve što se ispisuje je ili prepisano polje ili funkcija polja iz istog dokumenta
//      (zbir `use_len`, broj reči prompta, sat-format vremena) — izvedeno se ne može razići.
//
// Determinizam je zahtev verifikacije: dva pokretanja nad istim JSON-om daju bajt-identičan
// fajl. Otud: nigde `new Date()` (vreme se čita iz `generated_at`), nigde iteracija po
// neuređenom objektu (šest osa ide po `R1_AXES`), nigde `Object.keys` nad ulazom.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  R1_AXES, chainLetter, countWords, linkChains, loadStoryboard, plural, round3,
} from './contract.mjs';

export const HEADER =
  '<!-- GENERATED by tools/render.mjs — DO NOT EDIT. Source of truth: storyboard.json -->';

const slash = (p) => p.replace(/\\/g, '/');

/** Vrednost sa 3 decimale, bez repa nula: 6.5, 13.502, 23. */
const fmt = (t) => Number(t).toFixed(3).replace(/\.?0+$/, '');

/** Sekunde -> `0:06.5` / `12:03.2` / `1:04:11.0`. Za oko, ne za merenje. */
export function clock(t) {
  const total = Math.max(0, Number(t));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = (total % 60).toFixed(1).padStart(4, '0');
  return h ? `${h}:${String(m).padStart(2, '0')}:${s}` : `${m}:${s}`;
}

const range = (a, b) => `${clock(a)} → ${clock(b)}`;

/** Sve što je slobodan tekst ide kroz ovo — pipe bi razbio red tabele. */
const cell = (s) => String(s).replace(/\|/g, '\\|');

/** Blockquote koji preživi višerednu vrednost. */
const quote = (s) => String(s).split(/\r?\n/).map((l) => `> ${l}`).join('\n');

/**
 * Blok koda oko prompta. Ograda je duža od najdužeg niza obrnutih apostrofa u tekstu —
 * prompt sa ``` u sebi bi inače prelomio dokument na pola.
 */
export function fence(text) {
  const longest = Math.max(0, ...[...String(text).matchAll(/`+/g)].map((m) => m[0].length));
  const bars = '`'.repeat(Math.max(3, longest + 1));
  return `${bars}text\n${text}\n${bars}`;
}

const dash = (v) => (v === null || v === undefined || v === '' ? '—' : v);

/** Šest osa u kanonskom redosledu (schemas.md §3.5); nikad `Object.keys(tags)`. */
const tagLine = (tags) => R1_AXES.map((k) => `${k} \`${tags[k]}\``).join(' · ');

/**
 * @param {object} storyboard već proveren sa `assertDisplayable`
 * @returns {string} ceo `storyboard.md`, sa završnim prelomom reda
 */
export function renderStoryboard(storyboard) {
  const beats = storyboard.beats;
  const shots = beats.flatMap((b) => b.shots);
  const useSum = round3(shots.reduce((a, s) => a + s.use_len, 0));
  const drift = round3(Math.abs(useSum - storyboard.narration_duration));
  const tIn = shots[0].t_in;
  const tOut = shots.at(-1).t_out;

  const L = [
    HEADER,
    '',
    `# Storyboard — ${storyboard.episode}`,
    '',
    `- generisano: \`${storyboard.generated_at}\` · schema ${storyboard.schema_version} · ${storyboard.fps} fps`,
    `- ${beats.length} ${plural(beats.length, 'beat', 'beata', 'beatova')} · ` +
      `${shots.length} ${plural(shots.length, 'shot', 'shota', 'shotova')} · ` +
      `tajmlajn ${range(tIn, tOut)} (${fmt(tIn)} → ${fmt(tOut)}s)`,
    `- narracija ${fmt(storyboard.narration_duration)}s · zbir \`use_len\` ${fmt(useSum)}s · ` +
      `razlika ${fmt(drift)}s`,
    '',
    '| beat | vreme | trajanje | uređaj | shotovi |',
    '|---|---|---|---|---|',
  ];

  for (const b of beats) {
    L.push(`| ${b.beat_id} | ${range(b.start, b.end)} | ${fmt(b.dur)}s | ` +
      `${cell(dash(b.device))} | ${b.shots.map((s) => s.shot_id).join(', ')} |`);
  }

  for (const b of beats) {
    const chains = linkChains(b.shots);
    const linked = chains.filter((c) => c.group !== null);

    L.push('', '---', '',
      `## ${b.beat_id} · ${range(b.start, b.end)} · ${fmt(b.dur)}s · uređaj: ${dash(b.device)}`,
      '',
      `- rečenice: ${b.sentences.join(', ')}`,
      `- beat na tajmlajnu: ${fmt(b.start)} → ${fmt(b.end)}s`,
      `- shotovi: ${b.shots.map((s) => s.shot_id).join(', ')}` +
        (linked.length
          ? ` · lanac ${linked.map((c) => `${c.group} (${c.shots.map((s) => s.shot_id).join('+')})`).join(', ')} — spaja se dissolve-om`
          : ' · svi rezovi tvrdi'),
      '',
      '**NARRATION SAYS**',
      '',
      quote(b.narration_says),
      '',
      '**VIEWER SEES**',
      '',
      quote(b.viewer_sees));

    for (const c of chains) {
      c.shots.forEach((s, i) => {
        const inChain = c.group === null
          ? 'samostalan · tvrd rez'
          : `lanac ${c.group} (${chainLetter(i)} od ${c.shots.length})`;

        L.push('', `### shot ${s.shot_id} · ${range(s.t_in, s.t_out)} · ${fmt(s.use_len)}s · ${inChain}`,
          '',
          `- tajmlajn: ${fmt(s.t_in)} → ${fmt(s.t_out)}s`,
          `- klip: \`${s.source_file}\` · use ${fmt(s.use_in)} → ${fmt(s.use_out)}s ` +
            `(\`use_len\` ${fmt(s.use_len)}s)`,
          `- motion budget: ${s.motion_budget === null ? '—' : `${fmt(s.motion_budget)}s`}`,
          `- ingredient: ${s.ingredient_image === null ? '—' : `\`${s.ingredient_image}\``}`,
          `- likovi: ${s.characters.length ? s.characters.join(', ') : '—'}`,
          `- tags: ${tagLine(s.tags)}`,
          '',
          `**IMAGE PROMPT** · ${countWords(s.image_prompt)} reči`,
          '',
          fence(s.image_prompt),
          '',
          `**ANIMATION PROMPT** · ${countWords(s.animation_prompt)} reči`,
          '',
          fence(s.animation_prompt));
      });
    }
  }

  L.push('');
  return L.join('\n');
}

// ---------------------------------------------------------------- CLI

const USAGE = `node tools/render.mjs <folder-epizode> [opcije]

  storyboard.json -> <folder>/storyboard.md, čitljiv prikaz za ljude.
  Deterministički: dva pokretanja nad istim JSON-om daju identičan fajl.
  Fajl se nikad ne menja ručno — nosi DO-NOT-EDIT zaglavlje.

  --stdout      ispiši na stdout umesto u fajl
  -h, --help    ovaj tekst`;

export function parseArgs(argv) {
  const out = { dir: null, stdout: false, help: false };
  for (const a of argv) {
    if (a === '--stdout') out.stdout = true;
    else if (a === '-h' || a === '--help') out.help = true;
    else if (a.startsWith('-')) throw new Error(`nepoznata opcija ${a}\n\n${USAGE}`);
    else if (out.dir === null) out.dir = a;
    else throw new Error(`višak argumenta ${a}\n\n${USAGE}`);
  }
  if (!out.help && !out.dir) throw new Error(`nedostaje folder epizode\n\n${USAGE}`);
  return out;
}

export function main(argv) {
  const args = parseArgs(argv);
  if (args.help) {
    console.log(USAGE);
    return 0;
  }

  const { dir, storyboard } = loadStoryboard(args.dir);
  const md = renderStoryboard(storyboard);

  if (args.stdout) {
    process.stdout.write(md);
    return 0;
  }

  const outFile = path.join(dir, 'storyboard.md');
  fs.writeFileSync(outFile, md, 'utf8');
  const shots = storyboard.beats.reduce((a, b) => a + b.shots.length, 0);
  console.log(`-> ${slash(outFile)}`);
  console.log(`${storyboard.episode} · ${storyboard.beats.length} ` +
    `${plural(storyboard.beats.length, 'beat', 'beata', 'beatova')}, ` +
    `${shots} ${plural(shots, 'shot', 'shota', 'shotova')}`);
  return 0;
}

const invokedDirectly = process.argv[1]
  && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
  try {
    process.exit(main(process.argv.slice(2)));
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}
